### ISSUE TITLE
Automate generating `manifest.yml` file by the foraging GUI

### ISSUE THREAD

**Issue by hanhou** [AllenNeuralDynamics/dynamic-foraging-task#556]
To trigger the WatchDog service, the GUI should generate `manifest.yml` file for each session upon saving.
- See this issue: https://github.com/AllenNeuralDynamics/dynamic-foraging-task/issues/477
- Location: should be in the `flag_dir` defined in the `watch_dog.yml`. All manifest.yml files go into the same folder on the disk, i.e., not in their session folders.
- File name: could be `manifest_{session_id}.yml`
- Contents: example yml file that works
```yml
acquisition_datetime: 2024-06-21 13:54:00+00:00
name: behavior_724555_2024-06-21_13-54-00
platform: behavior
subject_id: 724555
capsule_id: null
mount: null
destination: //allen/aind/scratch/dynamic_foraging_rig_transfer
s3_bucket: private
processor_full_name: Han Hou
modalities:
  behavior:
  - C:/Users/admin/Documents/aind_watchdog_test/test_behavior_file/behavior_724555_2024-06-21_13-54-00/behavior
  behavior-videos:
  - C:/Users/admin/Documents/aind_watchdog_test/test_behavior_file/behavior_724555_2024-06-21_13-54-00/behavior-videos
  fib:
  - C:/Users/admin/Documents/aind_watchdog_test/test_behavior_file/behavior_724555_2024-06-21_13-54-00/fib
schemas:
  - C:/Users/admin/Documents/aind_watchdog_test/test_behavior_file/behavior_724555_2024-06-21_13-54-00/metadata-dir/session.json
  - C:/Users/admin/Documents/aind_watchdog_test/test_behavior_file/behavior_724555_2024-06-21_13-54-00/metadata-dir/rig.json
schedule_time: null
project_name: Behavior Platform
script: {}
```
- Notes:
    - use all forward slashes `/` in the paths
    - The file name of rig.json should be exactly `rig.json`, not `rig_447-1-A_xxx.json`.
    - `capsule_id` and `mount` should be added in the future when we want to trigger downstream NWB conversion etc.
    - maybe we should set `schedule_time` especially for sessions that have fib and video data
    - `project_name` should be one of [these](http://aind-metadata-service/project_names)
